### ISSUE TITLE
[Bug]: UserLocation doesn't work with other GeoLocation Services (Android)

### ISSUE THREAD

**Issue by 0xcD3v** [rnmapbox/maps#2717] opened 2023-03-18 00:13 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

10

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.11

### Standalone component to reproduce

```javascript
import { StyleSheet, View ,Text,PermissionsAndroid, SafeAreaView} from 'react-native';
import Mapbox, {UserLocationRenderMode} from '@rnmapbox/maps'
import { useEffect, useState } from "react";

export function Map(){

  const [location,setLocation] = useState(null);
  const [hasLocationPermissions,sethasLocationPermissions] = useState(false)

  const requestLocationPermission = async  () => 
  {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,

      )
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        sethasLocationPermissions(true)
        console.log("You can use the location")
        alert("You can use the location");
      } else {
        console.log("location permission denied")
        alert("Location permission denied");
      }
    } catch (err) {
      console.warn(err)
    }
  }

  useEffect(()=>{
      requestLocationPermission()
  },[])



    return(
        <SafeAreaView style={styles.container}>
             <Mapbox.MapView style={styles.map} >
              <Mapbox.PointAnnotation
                draggable={true}
                onDragEnd={feature => {
                  console.log(feature);
                  setLocation({
                    latitude: feature.geometry.coordinates[1],
                    longitude: feature.geometry.coordinates[0],
                  });
                }}
                coordinate={ [
                  -1.510311133796023,
                  53.816142903704616
                        ]}
              >
             <View style={{
                height: 30,
                width: 30,
                backgroundColor: '#00cccc',
                borderRadius: 50,
                borderColor: '#fff',
                borderWidth: 3
                }} />
      
     
              </Mapbox.PointAnnotation>
              
              
                
                    <Mapbox.UserLocation
                    visible={true}
                    androidRenderMode={'compass'}
                    showsUserHeadingIndicator={true}
                    onUpdate={newLocation => {
                      console.log(newLocation)
                    }}
                />
             
              
             
        </Mapbox.MapView>
        </SafeAreaView>
    )
}
```

### Observed behavior and steps to reproduce

This started when i switched to mac os, i have a project with rnmapbox and react-native-geolocation-service in linux android was working fine with both i could get updates from UserLocation but in mac os
that doesn't work anymore so i tried to figure out what was wrong, i started a new project and i could get update locations without react-native-geolocation-service installed, so i installed another lib  @react-native-community/geolocation and still happens the same the UserLocation didn't work anymore, i only can work with UserLocation on android without any geolocation lib.

**Comment by mfazekas** [comment] 2023-03-18 05:08
@0xcD3v I don't see 3rd party service in this example. Also what does doesn't work means, please be specific?

**Comment by 0xcD3v** [comment] 2023-03-18 11:46
> @0xcD3v I don't see 3rd party service in this example. Also what does doesn't work means, please be specific?

I don't need to call the 3rd party service on the code it just stoped works by having it installed. i change the location on simulator the user location component doesn't move, the onUpdate function doesn't get triggered. i tried on a physical device and happens the same it only work's in IOS

Portion of my package.json
<img width="537" alt="Screenshot 2023-03-18 at 11 34 00" src="https://user-images.githubusercontent.com/128076064/226103143-408d60b0-319d-4a18-8387-ea27581e7830.png">

my build.gradle 

<img width="633" alt="Screenshot 2023-03-18 at 11 40 27" src="https://user-images.githubusercontent.com/128076064/226103439-a64f63f4-6950-4c49-97bd-aa7c33e63a9c.png">

and i also have the api key on gradle.properties

i installed @rnmapbox via  yarn using this command: yarn add "rnmapbox/maps#main"

**Comment by 0xcD3v** [comment] 2023-03-18 13:03
@mfazekas i did a video showing what's happening 

https://user-images.githubusercontent.com/128076064/226107993-1f30bd84-009b-476a-9178-9bdc6a228b7e.mov

**Comment by 0xcD3v** [comment] 2023-03-21 20:13
@mfazekas hey, do you have updates about this issue? Do you need more information?

**Comment by mfazekas** [comment] 2023-03-22 06:31
@0xcD3v Sorry it's a community project, with limited resources.

**Comment by FrancoisVA** [comment] 2023-03-28 10:14
Hi, I'm experiencing the same issue. The UserLocation component's onUpdate function only fires once (on load) but doesn't fire again when the user location changes. Only occurs on Android.

I've tested on #main (latest MapBox version) and on 10.0.0-beta.76 and both had this issue. I will try older Beta versions now to see if one works.

To test, I'm building to my android device and then updating the location using the 'GPS emulator' app for Android, I find that this is the easiest and most reliable way to test the actual behaviour.

**Comment by mfazekas** [comment] 2023-03-28 10:27
@FrancoisVA thanks, are you also using other location services?

**Comment by FrancoisVA** [comment] 2023-03-28 13:50
@ [mfazekas](https://github.com/mfazekas) I tested on 10.0.0-beta.69, and the issue is not present there. There might be a more recent build (between 10.0.0-beta.69 and 10.0.0-beta.74) that also works, but I haven't had time to test on more versions.

**Comment by 0xcD3v** [comment] 2023-03-28 14:14
> @ [mfazekas](https://github.com/mfazekas) I tested on 10.0.0-beta.69, and the issue is not present there. There might be a more recent build (between 10.0.0-beta.69 and 10.0.0-beta.74) that also works, but I haven't had time to test on more versions.

I tried go to that version and the issue is still present for me. 

"yarn add @rnmapbox/maps@10.0.0-beta.69"

**Comment by FrancoisVA** [comment] 2023-03-30 10:36
> > @ [mfazekas](https://github.com/mfazekas) I tested on 10.0.0-beta.69, and the issue is not present there. There might be a more recent build (between 10.0.0-beta.69 and 10.0.0-beta.74) that also works, but I haven't had time to test on more versions.
> 
> I tried go to that version and the issue is still present for me.
> 
> "yarn add @rnmapbox/maps@10.0.0-beta.69"

@0xcD3v  I think it might be a cache issue with your package or something, but I don't know enough about RN to help you. Try deleting all packages and re-installing and cleaning the project I guess. I tried on 10.0.0-beta.70 and that works as well.

@mfazekas it looks like this issue is present on all versions after 10.0.0-beta.70, I guess some change between 70 and 71 is wat caused the issue. Please let me know if this is something you will be able to resolve or if we will have to get rid of the other geolocation packages.

**Comment by 0xcD3v** [comment] 2023-03-31 15:18
> > > @ [mfazekas](https://github.com/mfazekas) I tested on 10.0.0-beta.69, and the issue is not present there. There might be a more recent build (between 10.0.0-beta.69 and 10.0.0-beta.74) that also works, but I haven't had time to test on more versions.
> > 
> > 
> > I tried go to that version and the issue is still present for me.
> > "yarn add @rnmapbox/maps@10.0.0-beta.69"
> 
> @0xcD3v I think it might be a cache issue with your package or something, but I don't know enough about RN to help you. Try deleting all packages and re-installing and cleaning the project I guess. I tried on 10.0.0-beta.70 and that works as well.
> 
> @mfazekas it looks like this issue is present on all versions after 10.0.0-beta.70, I guess some change between 70 and 71 is wat caused the issue. Please let me know if this is something you will be able to resolve or if we will have to get rid of the other geolocation packages.

@FrancoisVA Is working for me now the 10.0.0-beta.70

**Comment by mfazekas** [comment] 2023-03-31 18:38
@FrancoisVA thank for checking looking at the diff of 70 and 71 https://github.com/rnmapbox/maps/compare/v10.0.0-beta.70...v10.0.0-beta.71 I see that mapbox was bumped to [10.11.1](https://github.com/rnmapbox/maps/commit/c6254b5f9e5a47811b4895a7bcc5b103c43bb6f8) If you can check if downgrading the mapbox libs with RNMapboxImpl as describe in docs helps or not:

https://github.com/rnmapbox/maps/blob/main/android/install.md#using-non-default-mapbox-version

```
 RNMapboxMapsLibs = {
            implementation 'com.mapbox.maps:android:10.10.0'
            implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0'
        }
```

**Comment by 0xcD3v** [comment] 2023-04-04 11:53
> @FrancoisVA thank for checking looking at the diff of 70 and 71 [v10.0.0-beta.70...v10.0.0-beta.71](https://github.com/rnmapbox/maps/compare/v10.0.0-beta.70...v10.0.0-beta.71) I see that mapbox was bumped to [10.11.1](https://github.com/rnmapbox/maps/commit/c6254b5f9e5a47811b4895a7bcc5b103c43bb6f8) If you can check if downgrading the mapbox libs with RNMapboxImpl as describe in docs helps or not:
> 
> https://github.com/rnmapbox/maps/blob/main/android/install.md#using-non-default-mapbox-version
> 
> ```groovy-gradle
>  RNMapboxMapsLibs = {
>             implementation 'com.mapbox.maps:android:10.10.0'
>             implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0'
>         }
> ```

@mfazekas I tried to do that, and the problem persists i updated to /maps-10.0.0-rc.8 and on ios i was unable to install " rnmapbox-maps (from `../node_modules/@rnmapbox/maps`) was resolved to 10.0.0-rc.8, which depends on
      MapboxMaps (~> 10.12.0)"

**Comment by FrancoisVA** [comment] 2023-04-05 08:53
> @FrancoisVA thank for checking looking at the diff of 70 and 71 [v10.0.0-beta.70...v10.0.0-beta.71](https://github.com/rnmapbox/maps/compare/v10.0.0-beta.70...v10.0.0-beta.71) I see that mapbox was bumped to [10.11.1](https://github.com/rnmapbox/maps/commit/c6254b5f9e5a47811b4895a7bcc5b103c43bb6f8) If you can check if downgrading the mapbox libs with RNMapboxImpl as describe in docs helps or not:
> 
> https://github.com/rnmapbox/maps/blob/main/android/install.md#using-non-default-mapbox-version
> 
> ```groovy-gradle
>  RNMapboxMapsLibs = {
>             implementation 'com.mapbox.maps:android:10.10.0'
>             implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:6.10.0'
>         }
> ```

Hi @mfazekas, sorry for the late reply. I tried jumping back onto rnmapbox/maps#main and setting the specific mapbox version in build.gradle, but the issue is still present. Did you see anything else that might cause the issue when you looked at the diff?

**Comment by Eagleames** [comment] 2023-04-06 14:24
This is also a problem I have been seeing intermittently for more than a year with our build. No one has been able to fix it so far; currently working with someone to try to build a work around for this case.  Any help in solving this would be amazing for us!

**Comment by 0xcD3v** [comment] 2023-04-13 13:32
hey guys from the same component i provide here, i  have another issue on IOS physical device. INVALID react tag, could not find RCTMGLMapView

**Comment by Gavin-PunchCard** [comment] 2023-04-17 15:30
It looks like there might be a solution found in another bug report by wen-kai:
https://github.com/rnmapbox/maps/issues/2543#issuecomment-1467447377

I added `useEffect(() => {MapboxGl.locationManager.start()},[]}` to the area's I'm using the MapboxGL.UserLocation and it seems to have fixed the issue for me.

**Comment by lowiebenoot** [comment] 2023-05-01 17:19
I'm having the same issue, but adding `useEffect(() => {MapboxGL.locationManager.start()},[]}` doesn't seem to do the trick for me.

Downgraded to `10.0.0-beta.70` and then it works again.

**Comment by emoreno-94** [comment] 2023-05-22 19:34
The same problem in v10.0.6. I tested with `10.0.0-beta.70` and the location works but I need to use sdf icons and in these version doesn't work

**Comment by kassemitani** [comment] 2023-05-30 10:45
Thank you @KiwiKilian This workaround worked for us, now UserLocation being updated on Android. 
 
```
      <MapboxGL.UserLocation
          minDisplacement={1}
          renderMode={UserLocationRenderMode.Normal}
        />
```

> Throughout this issue there are quite a few different/unclear problems stated. Therefore it's hard to determine, who is confirming which problem. I figured at least one specific case described by @FrancoisVA in our app too:
> 
> > The UserLocation component's onUpdate function only fires once (on load) but doesn't fire again when the user location changes. Only occurs on Android.
> 
> To further clarify, the puck on the map does not update for `normal` render mode (either custom children or the default from rnmapbox). Using `native` render mode will give a moving puck. For both render modes `onUpdate` is only triggered once. I'm on the `#main` Branch equivalent to `v10.0.7-rc.1`.
> 
> This occurs due to no `displacement` beeing passed. So anyone who's experiencing the `aforementioned` problem, please try the following:
> 
> ```tsx
>        <MapboxGL.UserLocation
>           minDisplacement={1}
>           renderMode={UserLocationRenderMode.Normal}
>           onUpdate={() => console.log("location changed")}
>         />
> ```
> 
> Please give feedback 👍 👎 if this workaround works (only if you are experiencing this very same problem). You should be seeing a moving puck and getting "location changed" regularly, if you are simulating/moving your location.
> 
> @mfazekas sadly I'm still not able to reproduce the bug in the example. I can only recreate it in our expo project. Through prebuild I added error logging to the [`LocationManager` `onFailure`](https://github.com/rnmapbox/maps/blob/a11bec7830997cd704d74fb4e8a4ef438929eddb/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/location/LocationManager.kt#L270) which gave the following error:
> 
> ```
> com.mapbox.common.location.compat.LocationEngineException: invalid displacement: -1.0
>         at com.mapbox.common.location.compat.LocationEngineImpl$notifyConsumersError$lambda-1$$inlined$postOrCall$1.run(LocationEngineImpl.kt:361)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> ```
> 
> So under some circumstances when displacement is passed as `-1.0` Mapbox SDK throws an error.

**Comment by yahyalrq** [comment] 2023-05-30 12:32
I encountered a similar error. Using react-native-geolocation-service 5.3.1 and rnmapbox v10.0.0-beta.64, there was no error. However when I added firebase as a dependency com.google.gms:google-services:4.3.15 I had the error Invalid Displacement -1,0 setSmallestDisplacement() with reference to the firebase dependency I had just installed. The error was related to using the userlocation in rnmpabox, which I fixed by upgrading to version 10.0.0-beta.69 !

**Comment by Tiropz** [comment] 2023-06-02 18:25
> Throughout this issue there are quite a few different/unclear problems stated. Therefore it's hard to determine, who is confirming which problem. I figured at least one specific case described by @FrancoisVA in our app too:
> 
> > The UserLocation component's onUpdate function only fires once (on load) but doesn't fire again when the user location changes. Only occurs on Android.
> 
> To further clarify, the puck on the map does not update for `normal` render mode (either custom children or the default from rnmapbox). Using `native` render mode will give a moving puck. For both render modes `onUpdate` is only triggered once. I'm on the `#main` Branch equivalent to `v10.0.7-rc.1`.
> 
> This occurs due to no `displacement` beeing passed. So anyone who's experiencing the `aforementioned` problem, please try the following:
> 
> ```tsx
>        <MapboxGL.UserLocation
>           minDisplacement={1}
>           renderMode={UserLocationRenderMode.Normal}
>           onUpdate={() => console.log("location changed")}
>         />
> ```
> 
> Please give feedback 👍 👎 if this workaround works (only if you are experiencing this very same problem). You should be seeing a moving puck and getting "location changed" regularly, if you are simulating/moving your location.
> 
> @mfazekas sadly I'm still not able to reproduce the bug in the example. I can only recreate it in our expo project. Through prebuild I added error logging to the [`LocationManager` `onFailure`](https://github.com/rnmapbox/maps/blob/a11bec7830997cd704d74fb4e8a4ef438929eddb/android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/location/LocationManager.kt#L270) which gave the following error:
> 
> ```
> com.mapbox.common.location.compat.LocationEngineException: invalid displacement: -1.0
>         at com.mapbox.common.location.compat.LocationEngineImpl$notifyConsumersError$lambda-1$$inlined$postOrCall$1.run(LocationEngineImpl.kt:361)
>         at android.os.Handler.handleCallback(Handler.java:883)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> ```
> 
> So under some circumstances when displacement is passed as `-1.0` Mapbox SDK throws an error.

Had the issue and setting minDisplacement={0} solved it. In doc, it is still said that default is 0 !

**Comment by muhammadshaheer-er** [comment] 2023-07-24 10:19
Using Mapbox version  10.0.0-beta.70 does not make a difference for me. I am using "react-native-background-geolocation": "^4.10.0", 

anyone found other solutions?

**Comment by Tiropz** [comment] 2023-07-24 11:23
> Using Mapbox version 10.0.0-beta.70 does not make a difference for me. I am using "react-native-background-geolocation": "^4.10.0",
> 
> anyone found other solutions?

I'm using `import {UserLocation} from '@rnmapbox/maps;`
and `
        <UserLocation
          androidRenderMode={'gps'}
          renderMode={UserLocationRenderMode.Native}
          showsUserHeadingIndicator={true}
          visible={true}
          requestsAlwaysUse={true}
          minDisplacement={1}
          animated={true}
        />`

And it works fine

**Closed** 2023-10-01 01:02 UTC
Labels: bug 🪲
