### ISSUE TITLE
[Bug]: followUserLoction doesn't work on intial load on Android

### ISSUE THREAD

**Issue by KiwiKilian** [rnmapbox/maps#2538] opened 2023-01-11 09:57 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

```tsx
import MapboxGL, { Camera, MapView } from '@rnmapbox/maps';
import React, { useState } from 'react';
import { Button } from 'react-native';

import { UserTrackingMode } from '../../../javascript/components/Camera';
import sheet from '../styles/sheet';

const BugReportExample = () => {
  const [followUserMode, setFollowUserMode] = useState<
    UserTrackingMode | undefined
  >(UserTrackingMode.Follow);

  return (
    <>
      {Object.values(UserTrackingMode).map((mode) => (
        <Button
          key={mode}
          title={`${mode} ${mode === followUserMode ? '(active)' : ''}`}
          onPress={() => setFollowUserMode(mode)}
        />
      ))}
      <MapView style={sheet.matchParent}>
        <MapboxGL.UserLocation visible showsUserHeadingIndicator />

        <Camera
          defaultSettings={{
            centerCoordinate: [-111.8678, 40.2866],
            zoomLevel: 0,
          }}
          followUserLocation
          followUserMode={followUserMode}
          onUserTrackingModeChange={(event) => {
            console.log(event.nativeEvent.payload);

            setFollowUserMode(
              event.nativeEvent.payload.followUserMode || undefined,
            );
          }}
        />
      </MapView>
    </>
  );
};

export default BugReportExample;

```

### Observed behavior and steps to reproduce

The user isn't followed when initially opening the example. A change of follow mode is necessary to fix this.

### Expected behavior

The user should be followed from the beginning, just like on iOS.

### Notes / preliminary analysis

https://github.com/rnmapbox/maps/issues/237 looks similar?

### Additional links and references

Might also be connected or fixed togehter with https://github.com/rnmapbox/maps/issues/1090#issuecomment-1378488993.

**Comment by cjlynch12** [comment] 2023-01-12 18:02
Also seeing this issue on `10.0.0-beta.58`, and can confirm the fix above (updating `followUserMode`) is required to center on user location and follow as intended.

**Comment by mfazekas** [comment] 2023-02-26 15:24
This seems to be fixed in beta70.

**Closed by mfazekas** 2023-02-26 15:24 UTC
Labels: bug 🪲, Android
