### ISSUE TITLE
[Bug]: MapboxLibraryLoader.load java.lang.UnsatisfiedLinkError - couldn't find "libmapbox-common.so"

### ISSUE THREAD

**Issue by rizki-tabist** [rnmapbox/maps#3270] opened 2023-12-14 02:08 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

^10.0.15

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@rnmapbox/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

Sporadic crashes were reported via crashlytics when loading Mapbox libraries.
<img width="1132" alt="Screenshot 2023-12-14 at 09 04 03" src="https://github.com/rnmapbox/maps/assets/133627907/5687903d-aa67-402c-86f8-d6ea48f189a7">

It seems the issue comes from Mapbox Map Android itself

### Expected behavior

No crash

### Additional links and references

[Sporadic crashes when Mapbox library is loaded: java.lang.UnsatisfiedLinkError at com.mapbox.common.loader.MapboxLibraryLoader.load #1109](https://github.com/mapbox/mapbox-maps-android/issues/1109)

**Comment by mfazekas** [comment] 2023-12-14 20:45
Thanks much for the info. 
The issue is not really actionable for us, hopefully it'll be fixed in upstream mapbox-maps-android

**Closed by mfazekas** 2023-12-14 20:45 UTC
Labels: bug 🪲, upstream, Android
