### ISSUE TITLE
> Task :rnmapbox_maps:compileReleaseKotlin FAILED when building apk 

### ISSUE THREAD

**Issue by LucasWilliams2622** [rnmapbox/maps#3388] opened 2024-02-22 07:38 UTC
I tested it on a virtual machine and everything was fine, but when I built the apk, this error appeared

> Task :rnmapbox_maps:compileReleaseKotlin
e: file:///Users/isc_one/Desktop/GitHub/ISLink/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXMarkerView.kt:183:19 Type mismatch: inferred type is Double but Int? was expected
e: file:///Users/isc_one/Desktop/GitHub/ISLink/node_modules/@rnmapbox/maps/android/src/main/java/com/rnmapbox/rnmbx/components/annotation/RNMBXMarkerView.kt:184:20 Type mismatch: inferred type is Double but Int? was expected
...
e: file:///Users/isc_one/Desktop/GitHub/ISLink/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v11/com/rnmapbox/rnmbx/v11compat/Snapshot.kt:21:17 Unresolved reference: _toMapboxImage
e: file:///Users/isc_one/Desktop/GitHub/ISLink/node_modules/@rnmapbox/maps/android/src/main/mapbox-v11-compat/v11/com/rnmapbox/rnmbx/v11compat/StyleFactory.kt:7:22 Type mismatch: inferred type is Expression but Int was expected

> Task :rnmapbox_maps:compileReleaseKotlin FAILED 

When I researched, the error came from the RNMBXStyleFatory file in 2 lines import import com.mapbox.maps.extension.style.atmosphere.generated.Atmosphere
  and import com.mapbox.maps.extension.style.layers.generated.ModelLayer

![Screenshot 2024-02-22 at 14 35 48](https://github.com/rnmapbox/maps/assets/101234675/9304a408-f899-4fb2-b684-873e243aa8a0)

**Comment by mfazekas** [comment] 2024-02-23 16:46
Hi, thanks for the report! To be able to look into setup related issues we need full steps to reproduce the issue. 
Ideally n a brand new project, in the form of
```
react-native init sample --version react-native@0.67.5
cd sample
npm install @rnmapbox/maps --save
cd ios
pod installl
...
react-native run-ios
```

closing the issue now, will reopen when you provide the steps to reproduce.
If you cannot reproduce with a  brand new project, please start a new project with the same rn version you have and compare package.json for different versions.

Please note that your issue is considered a [support request](https://github.com/rnmapbox/maps/wiki/Support) and we don't provide free [support](https://github.com/rnmapbox/maps/wiki/Support).

**Closed by mfazekas** 2024-02-23 16:46 UTC
Labels: bug-setup 🪲

**Comment by LucasWilliams2622** [comment] 2024-02-24 07:28
> Hi, thanks for the report! To be able to look into setup related issues we need full steps to reproduce the issue. Ideally n a brand new project, in the form of
> 
> ```
> react-native init sample --version react-native@0.67.5
> cd sample
> npm install @rnmapbox/maps --save
> cd ios
> pod installl
> ...
> react-native run-ios
> ```
> 
> closing the issue now, will reopen when you provide the steps to reproduce. If you cannot reproduce with a brand new project, please start a new project with the same rn version you have and compare package.json for different versions.
> 
> Please note that your issue is considered a [support request](https://github.com/rnmapbox/maps/wiki/Support) and we don't provide free [support](https://github.com/rnmapbox/maps/wiki/Support).

Hi, Thanks for the reply, I have installed @rnmapbox/maps and run it on the ios virtual machine but when I run it on the android virtual machine it shows compileReleaseKotlin FAILED error. my project is using react native 0.72.6 and I have configured enough according to https://rnmapbox.github.io/docs/install?rebuild=ios&v11-instructions=ios&configure-module=android&install-module=yarn&location=android
