### ISSUE TITLE
[Bug]: Could not invoke RTMGLLocationModule.start - Error on UserLocation

### ISSUE THREAD

**Issue by lukssds** [rnmapbox/maps#3046] opened 2023-09-13 12:48 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

10

### Platform

Android

### `@rnmapbox/maps` version

10.0.12

### Standalone component to reproduce

```javascript
import React, {useState} from 'react';
import Mapbox from '@rnmapbox/maps';

const [userLocation, setUserLocation] = useState([0.0, 0.0]);
const [isPermissionGranted, setIsPermissionsGranted] = useState(false)

{isPermissionGranted &&
  <Mapbox.UserLocation
    minDisplacement={2} 
    onUpdate={(location) => {
      setUserLocation([location.coords.longitude, location.coords.latitude]);
    }}
  >
    <Mapbox.SymbolLayer
      id={'iconUserLocation'}
      style={{
        iconPitchAlignment: 'map',
        iconImage: 'arrow',
        iconSize: 0.14,
        iconRotate:0,
        iconAllowOverlap: true,
      }}
    />
    <Mapbox.CircleLayer
      id={'circle'}
      style={{
        circleColor:'rgba(255,255,225,0.3)',
        circleRadius: 60,
        circlePitchScale: 'map',
        circlePitchAlignment: 'map',
      }}
    />
  </Mapbox.UserLocation>
}
```

### Observed behavior and steps to reproduce

This issue started happening on Friday 08/09/23 (day/month/year), and I don't know why, but the problem seems to be userLocation, when I comment out all the code from Mapbox userlocation, the error doesn't appear, but I'm not able to use the user location update or even append the user indicator to the screen. I think that it could be related to #2717, but I've tried every single response to this problem in that issue with no success. I'm using '@react-native-community/geolocation' to get the user's location as well.

![Screenshot_20230912_174405](https://github.com/rnmapbox/maps/assets/64933717/80d7dba3-1a25-4970-9b76-a891784f39ab)

**Comment by hexadecy** [comment] 2023-09-19 21:20
I have this issue on Android but only when @react-native-community/geolocation is at 3.1.0.
@rnmapbox/maps: 10.0.15
https://github.com/michalchudziak/react-native-geolocation/compare/v3.0.6...v3.1.0
It seems to be a conflict.

**Comment by RayanCardoso** [comment] 2023-09-27 17:15
I had the problem "Invalid displacement" when I try to put only UserLocation on MapView. Someone with the same error?

**Comment by lukssds** [comment] 2023-09-27 18:41
Hey @RayanCardoso I also faced this issue, for me the only thing that worked was to make sure that I was rendering the UserLocation component after I had all the location permissions I don't kown other way around it.
For that I've created a state that changes to true when my permissions are granted, and I only render my UserLocation if that state is true

I also tried everything in that issue here https://github.com/rnmapbox/maps/issues/2717#issuecomment-1568121651  but nothing worked

**Comment by hexadecy** [comment] 2023-09-27 19:36
Make sure you have minDisplacement for Android.
`<MapboxGL.UserLocation visible={hasLocationPermission} minDisplacement={10} />`

**Comment by RayanCardoso** [comment] 2023-09-28 12:11
Thanks @hexadecy and @lukssds that worked for me.

**Comment by mfazekas** [comment] 2023-09-30 16:16
@lukssds sorry can you add a full component, with MapView? I cannot run your code as is. Thanks!

**Comment by mfazekas** [comment] 2023-09-30 18:01
Sounds like duplicate of: #2717

**Closed by mfazekas** 2023-09-30 18:01 UTC
Labels: Needs: Author Feedback
