### ISSUE TITLE
cannot find 'RCTMGLSwiftLog' in scope

### ISSUE THREAD

**Issue by MariuzM** [rnmapbox/maps#3150] opened 2023-10-31 06:38 UTC
## Environment
- macOS
- Bun
- Expo

## Steps to reproduce

```sh   
expo run:ios
```

Out of the blue i started getting these errors for iOS 

```
❌  (node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTLog.swift:2:3)

  1 | func RCTMGLLogError(_ message: String, _ file: String=#file, _ line: UInt=#line) {
> 2 |   RCTMGLSwiftLog.error(message, file: file, line: line)
    |   ^ cannot find 'RCTMGLSwiftLog' in scope
  3 | }
  4 | 
  5 | func RCTMGLLogWarn(_ message: String, _ file: String=#file, _ line: UInt=#line) {


❌  (node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTLog.swift:6:3)

  4 | 
  5 | func RCTMGLLogWarn(_ message: String, _ file: String=#file, _ line: UInt=#line) {
> 6 |   RCTMGLSwiftLog.warn(message, file: file, line: line)
    |   ^ cannot find 'RCTMGLSwiftLog' in scope
  7 | }
  8 | 
  9 | func RCTMGLLogInfo(_ message: String, _ file: String=#file, _ line: UInt=#line) {


❌  (node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTLog.swift:10:3)

   8 | 
   9 | func RCTMGLLogInfo(_ message: String, _ file: String=#file, _ line: UInt=#line) {
> 10 |   RCTMGLSwiftLog.info(message, file: file, line: line)
     |   ^ cannot find 'RCTMGLSwiftLog' in scope
  11 | }
  12 | 
  13 | func RCTMGLLog(_ message: String, _ file: String=#file, _ line: UInt=#line) {


❌  (node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTLog.swift:14:3)

  12 | 
  13 | func RCTMGLLog(_ message: String, _ file: String=#file, _ line: UInt=#line) {
> 14 |   RCTMGLSwiftLog.log(message, file: file, line: line)
     |   ^ cannot find 'RCTMGLSwiftLog' in scope
  15 | }
  16 | 
  17 | func RCTMGLLogTrace(_ message: String, _ file: String=#file, _ line: UInt=#line) {


❌  (node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTLog.swift:18:3)

  16 | 
  17 | func RCTMGLLogTrace(_ message: String, _ file: String=#file, _ line: UInt=#line) {
> 18 |   RCTMGLSwiftLog.trace(message, file: file, line: line)
     |   ^ cannot find 'RCTMGLSwiftLog' in scope
  19 | }
```

On android it works fine. i even went back to previous commit of the project and those not working also. I have changed the private key just in case still same, really unsure what is happening here. 

Example:

```jsx
import Mapbox from '@rnmapbox/maps';
import React from 'react';
import { StyleSheet, View } from 'react-native';

const App = () => {
  return (
    <View style={styles.container}>
      <Mapbox.MapView
        style={styles.map}
        onPress={(feature) => console.log('Coords:', feature.geometry)}
      >
        <Mapbox.PointAnnotation
          id="pointAnnotation"
          coordinate={[-0.29296964120311486, 5.9948919351710686]}
          onSelected={() => {
            // console.log('onSelected', item.id);
          }}
        >
          <View style={{ backgroundColor: 'red', width: 30, height: 30 }} />
          <Mapbox.Callout title="test" />
        </Mapbox.PointAnnotation>
      </Mapbox.MapView>
    </View>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
  },
  map: {
    flex: 1,
  },
});
```

**Comment by MariuzM** [comment] 2023-10-31 06:58
10.1.0-beta.5 fixed it

**Comment by MariuzM** [comment] 2023-10-31 07:04
[v10.1.0-beta.15](https://github.com/rnmapbox/maps/releases/tag/v10.1.0-beta.15)  also works fine

**Comment by mfazekas** [comment] 2023-11-03 06:51
Hi, thanks for the report! To be able to look into setup related issues we need full steps to reproduce the issue. 
Ideally n a brand new project, in the form of
```
react-native init sample --version react-native@0.67.5
cd sample
npm install @rnmapbox/maps --save
cd ios
pod installl
...
react-native run-ios
```

closing the issue now, will reopen when you provide the steps to reproduce.
If you cannot reproduce with a  brand new project, please start a new project with the same rn version you have and compare package.json for different versions.

Please note that your issue in current form is considered a [support request](https://github.com/rnmapbox/maps/wiki/Support) and we don't provide free [support](https://github.com/rnmapbox/maps/wiki/Support).

**Closed by mfazekas** 2023-11-03 06:51 UTC
