### ISSUE TITLE
[Bug]: NewArch Exception in HostFunction: no non-static method updateCameraStop

### ISSUE THREAD

**Issue by IASV** [rnmapbox/maps#3537] opened 2024-06-19 21:11 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

10.1.27

### React Native Version

0.74.2

### Platform

Android

### `@rnmapbox/maps` version

10.1.27

### Standalone component to reproduce

```javascript
import React, { useRef, useEffect } from 'react';
import { Camera } from '@rnmapbox/maps';

const CENTER_COORDINATE = [-70.60133170151073, -33.48883453771556]
const ZOOM_LEVEL = 18.149781801261174

const BugReportExample = () => {
  const camera = useRef<Camera>(null);

  useEffect(() => {
    if (camera.current) {
      camera.current.setCamera({
        centerCoordinate: CENTER_COORDINATE,
        zoomLevel: ZOOM_LEVEL
      });
    }
  }, []);

  return <Camera ref={camera} />;
};

export default BugReportExample;
```

### Observed behavior and steps to reproduce

Error
```console
Error: Exception in HostFunction: no non-static method "Lcom/rnmapbox/rnmbx/components/camera/RNMBXCameraModule;.updateCameraStop(Ljava/lang/Double;Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V"
```

When the new architecture is activated, it starts giving the error, once it is deactivated, the error disappears.

```javascript
camera.current.setCamera(...) //error
camera.current.flyTo(...) //error
camera.current.zoomTo(...) //error
```

**node_moduels -> CameraModule.kt**
```javascript
import com.rnmapbox.rnmbx.utils.ViewRefTag
//more imports...

class RNMBXCameraModule(context: ReactApplicationContext, val viewTagResolver: ViewTagResolver) : NativeRNMBXCameraModuleSpec(context) {
    private fun withViewportOnUIThread(
        viewRef: ViewRefTag?,
        reject: Promise,
        fn: (RNMBXCamera) -> Unit
    ) {
        if (viewRef == null) {
            reject.reject(Exception("viewRef is null"))
        } else {
            viewTagResolver.withViewResolved(viewRef.toInt(), reject, fn)
        }
    }

    private fun createCommandResponse(promise: Promise): CommandResponse = object : CommandResponse {
        override fun success(builder: (WritableMap) -> Unit) {
            val payload: WritableMap = WritableNativeMap()
            builder(payload)

            promise.resolve(payload)
        }

        override fun error(message: String) {
            promise.reject(Exception(message))
        }
    }

    companion object {
      const val NAME = "RNMBXCameraModule"
    }

    override fun updateCameraStop(viewRef: ViewRefTag?, stop: ReadableMap, promise: Promise) {
        withViewportOnUIThread(viewRef, promise) {
            it.updateCameraStop(stop)
            promise.resolve(null)
        }
    }
}
```

**node_moduels -> NativeRNMBXCameraModule.ts**
```javascript
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { Int32 } from 'react-native/Libraries/Types/CodegenTypes';
import { TurboModuleRegistry } from 'react-native';

type ViewRef = Int32 | null;

interface NativeCameraStop {
  centerCoordinate?: string;
  bounds?: string;
  heading?: number;
  pitch?: number;
  zoom?: number;
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  paddingBottom?: number;
  duration?: number;
  mode?: NativeAnimationMode;
}

type Stop =
  | {
      stops: NativeCameraStop[];
    }
  | NativeCameraStop;

type NativeAnimationMode = 'flight' | 'ease' | 'linear' | 'none' | 'move';

// eslint-disable-next-line @typescript-eslint/ban-types, @typescript-eslint/no-unused-vars
type ObjectOr<T> = Object;

export interface Spec extends TurboModule {
  updateCameraStop(viewRef: ViewRef, stop: ObjectOr<Stop>): Promise<void>;
}

export default TurboModuleRegistry.getEnforcing<Spec>('RNMBXCameraModule');
```

### Additional links and references

![image](https://github.com/rnmapbox/maps/assets/64744290/00c7f19e-cb27-4383-b7eb-e3beb9d34451)

**Comment by mfazekas** [comment] 2024-06-20 13:54
@IASV duplicate of #3522 

It's a bug in react-native 0.74, see my comment at #3522. As a workaround you can use patch-packages to fix the issue in react-native, see my last comment in #3522

**Closed by mfazekas** 2024-06-20 13:54 UTC
Labels: bug 🪲
