### ISSUE TITLE
[Bug]: NewArch: Exception in setHandledMapChangedEvents when loading the map in RN 0.74.2

### ISSUE THREAD

**Issue by kubabutkiewicz** [rnmapbox/maps#3522] opened 2024-06-12 19:23 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### React Native Version

0.74.2

### Platform

Android

### `@rnmapbox/maps` version

10.1.23

### Standalone component to reproduce

```javascript
// I couldn't reproduce it in example app
export default () => {}
```

### Observed behavior and steps to reproduce

We are working in [Expensify](https://github.com/Expensify/App/tree/cb02bb36985f0fdf7141ef47989af6879032429b) on upgrading RN version to 0.74.2 and we noticed the crash caused by rnmapbox. When we navigating to screen when we are displaying map we are getting this error `Error: Exception in HostFunction: no non-static method "Lcom/rnmapbox/rnmbx/components/mapview/NativeMapViewModule;.setHandledMapChangedEvents(Ljava/lang/Double;Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/Promise;)V" `. More context and logs are [here](https://github.com/Expensify/App/pull/40548#issuecomment-2160697398). 

### Additional links and references

https://github.com/rnmapbox/maps/assets/25230417/0139bcc8-14a8-4ede-bc0a-47b20268dca7

_No response_

**Comment by mfazekas** [comment] 2024-06-14 04:54
Should be fixed by #3527, there might be further similar issues

**Comment by mfazekas** [comment] 2024-06-19 04:35
See https://github.com/facebook/react-native/pull/45024
https://github.com/facebook/react-native/issues/44963

As expected there other issues as well.

https://github.com/rnmapbox/maps/issues/3511#issuecomment-2176958611

Could be worked around with patch-package, see https://github.com/mfazekas/maps-1/commit/dbcf2b182ff86c1473f8cb207c459100ffee6018 for example

**Comment by roryabraham** [comment] 2024-07-12 17:28
Looks like the upstream issue may have been fixed in https://github.com/facebook/react-native/commit/8a6b88eeafef4eb63ee537c4ce71f9928f81a766, though it doesn't look like that has been included in a release yet

**Comment by mfazekas** [comment] 2024-07-13 14:34
@roryabraham so it's a bit complicated. So the issue is that in RN 0.73 what was Int32 in typescript Native codespec  in  was generated as Double. 
In RN 0.74 this was fixed so Int32 in typescript, generated Long etc on native side. But this was not 100% change and runtime was looking for Double on android side. The plan was to fix that, but because of backward compatibility it was decided to go back 0.73 where Int32 is Double. This is something I see even in RN 0.75.rc*. Not sure about 0.74.3, will check.

I guess RN 0.76 will go with Int32 -> Long.

**Comment by mfazekas** [comment] 2024-07-13 14:48
So it looks like codegen is fixed  (aka reverted back to java Double) in RN 0.74.3 - see #3570.

**Closed** 2024-07-13 15:54 UTC
Labels: bug 🪲
