### ISSUE TITLE
Module 'Mapbox' not found

### ISSUE THREAD

**Issue by TulsiRajput21** [rnmapbox/maps#2542] opened 2023-01-13 05:52 UTC
## Environment
- Dev OS: [e.g. OSX 11.0.1, Win10]

## Steps to reproduce

```sh   
react-native init sample --version react-native@0.60.5
cd sample
npm install rnmapbox/maps#main --save
# or released version `npm install @rnmapbox/maps@8.0.0-rc1 --save`
react-native run-android
```

**Comment by mfazekas** [comment] 2023-01-14 17:41
Duplicate of #2309

**Closed by mfazekas** 2023-01-14 17:41 UTC
