### ISSUE TITLE
StyleURL has no effect on ios when using Mapview with expo

### ISSUE THREAD

**Issue by dev-plainsight** [rnmapbox/maps#1836] opened 2022-04-15 11:47 UTC
**Describe the bug**  
Setting StyleURL prop of MapboxGL.MapView does not seem to have any effect. The most displayed detail is country names.
All of these attempts result in the map in the screenshot
styleURL={MapboxGL.StyleURL.Street}
styleURL={MapboxGL.StyleURL.Dark}
styleURL={MapboxGL.StyleURL.Light}
styleURL={MapboxGL.StyleURL.Satellite}
**To Reproduce**  
Steps to reproduce the behavior. 
npm install rnmapbox/maps#main

add plugin:  [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "maplibre",
          "RNMapboxMapsDownloadToken": "sk.ey...qg"
        }
      ]

run command expo run:ios or react-native run-ios

Please include a single standalone React Native component.  
Use [our BugReportTemplate](https://github.com/rnmapbox/maps/blob/main/example/src/examples/BugReportTemplate.js) screens as a starting point.
Please simplify the example as much as possible!

Chances that a bug report will be investiagete and worked on are exponetially higher with a complete and _working_ repro BugTemplate!

Example:
```js
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import MapboxGL from "@rnmapbox/maps";

MapboxGL.setAccessToken(
  "Mytoken"
);

export default class MiniMap extends Component {
  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }
  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView
            style={styles.map}
            styleURL={MapboxGL.StyleURL.Street}
            animate={true}
            compassEnabled={true}
            compassViewMargins={{ x: 59, y: 17 }}
          >
            <MapboxGL.Camera zoomLevel={3} centerCoordinate={[17, 59]} />
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  page: {
    height: "100%",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
  },
  container: {
    height: "100%",
    width: "100%",
  },
  map: { height: "100%", width: "100%" },
});

```

**Expected behavior**  
The map should display the street names and graphics when zoomed in. It should also change colour when style is changed between for example Light and Dark like below.
styleURL={MapboxGL.StyleURL.Dark}
styleURL={MapboxGL.StyleURL.Light}

**Actual behavior**  
A clear and concise description of what is currently happening.
The map displays what I understand is some default style where only country names are displayed on a different coloured country background.

**Screenshots**  
https://imgur.com/a/3JFKOSb

**Versions (please complete the following information):**  
 - Platform: [e.g. Android, iOS] iOS
 - Platform OS: [e.g. Android 9, iOS 10] Physical iphone 11 running ios 15.3.1 and simulated iphone 12 running 14.5
 - Device: [e.g. iPhone6]  iphone 11 / 12
 - Emulator/ Simulator: [yes/ no] both
 - Dev OS: [e.g. OSX 11.0.1, Win10] MacOS Monterey 12.0.1 m1
 - @rnmapbox/maps Version [e.g. 10.0.1] 10.0.0-beta.1
 - Mapbox GL version [e.g. 6.3.0] 2.8.1
 - React Native Version [e.g. 0.59] 0.64.3

**Additional context**

**Comment by mfazekas** [comment] 2022-04-16 11:39
Duplicate of: #1840

**Closed by mfazekas** 2022-04-16 11:39 UTC
