### ISSUE TITLE
[Bug]: App crashes when using expression for textAnchor

### ISSUE THREAD

**Issue by ryanpwaldon** [rnmapbox/maps#2871] opened 2023-05-19 05:18 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

10.11.1

### Platform

iOS

### `@rnmapbox/maps` version

10.0.6

### Standalone component to reproduce

```typescript
import { View } from 'react-native'
import Mapbox from '@rnmapbox/maps'
import { type SymbolLayerStyleProps } from '@rnmapbox/maps/src/utils/MapboxStyles'

const feature = {
  type: 'Feature',
  properties: {
    id: 'clgnqq4xc00v4bpxv7hs9m5kt',
    name: 'Soldiers Beach',
    textAnchor: 'right',
  },
  geometry: {
    type: 'Point',
    coordinates: [151.564602, -33.291277],
  },
} satisfies GeoJSON.Feature

const featureCollection = {
  type: 'FeatureCollection',
  features: [feature],
} satisfies GeoJSON.FeatureCollection

export default function Map() {
  return (
    <View style={{ width: '100%', height: '100%' }}>
      <Mapbox.MapView style={{ width: '100%', height: '100%' }}>
        <Mapbox.Camera animationMode="moveTo" centerCoordinate={feature.geometry.coordinates} zoomLevel={14} />
        <Mapbox.ShapeSource id="source" shape={featureCollection}>
          <Mapbox.SymbolLayer
            id="layer"
            style={
              {
                iconImage: 'badge',
                textColor: 'black',
                textField: ['get', 'name'],
                textFont: ['DIN Pro Medium'],
                textSize: 12,
                textAnchor: ['get', 'textAnchor'], // <--- app crashes when using expression
                textOffset: [0.75, 0],
              } as SymbolLayerStyleProps
            }
          />
        </Mapbox.ShapeSource>
        <Mapbox.Images>
          <Mapbox.Image name="badge">
            <View style={{ justifyContent: 'center', alignItems: 'center', width: 12, height: 12 }}>
              <View style={{ width: 6, height: 6, borderColor: 'black', borderWidth: 1, borderRadius: 6, backgroundColor: 'white' }} />
            </View>
          </Mapbox.Image>
        </Mapbox.Images>
      </Mapbox.MapView>
    </View>
  )
}
```

### Observed behavior and steps to reproduce

App crashes when setting `textAnchor` to an expression in a `SymbolLayer`. Works fine with string values. I'm using Expo. No errors are thrown, the app simply crashes and returns to iOS home screen.

**Comment by mfazekas** [comment] 2023-05-26 20:49
@ryanpwaldon thanks much for the report I could reproduce it with the provided example. We don't seem to support expression for style with enum values. This should be fixed.

```js
import React from 'react';
import { View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

const feature = {
  type: 'Feature',
  properties: {
    id: 'clgnqq4xc00v4bpxv7hs9m5kt',
    name: 'Soldiers Beach',
    textAnchor: 'right',
  },
  geometry: {
    type: 'Point',
    coordinates: [151.564602, -33.291277],
  },
};

const featureCollection = {
  type: 'FeatureCollection',
  features: [feature],
};

export default function Map() {
  return (
    <View style={{ width: '100%', height: '100%' }}>
      <Mapbox.MapView style={{ width: '100%', height: '100%' }}>
        <Mapbox.Camera
          animationMode="moveTo"
          centerCoordinate={feature.geometry.coordinates}
          zoomLevel={14}
        />
        <Mapbox.ShapeSource id="source" shape={featureCollection}>
          <Mapbox.SymbolLayer
            id="layer"
            style={{
              iconImage: 'badge',
              textColor: 'black',
              textField: ['get', 'name'],
              textFont: ['DIN Pro Medium'],
              textSize: 12,
              textAnchor: ['get', 'textAnchor'], // <--- app crashes when using expression
              textOffset: [0.75, 0],
            }}
          />
        </Mapbox.ShapeSource>
        <Mapbox.Images>
          <Mapbox.Image name="badge">
            <View
              style={{
                justifyContent: 'center',
                alignItems: 'center',
                width: 12,
                height: 12,
              }}
            >
              <View
                style={{
                  width: 6,
                  height: 6,
                  borderColor: 'black',
                  borderWidth: 1,
                  borderRadius: 6,
                  backgroundColor: 'white',
                }}
              />
            </View>
          </Mapbox.Image>
        </Mapbox.Images>
      </Mapbox.MapView>
    </View>
  );
}
```

**Comment by bisak** [comment] 2023-05-30 16:02
Hey @mfazekas, - "We don't seem to support expression for style with enum values"

Could this be the reason apps crash (iOS only) when using the `Images` component and `iconImage: the-image-key` within a `SymbolLayer`'s style?

Fails with `Exception thrown while executing UI block... RCTMGLImages... unrecognized selector sent to instance`

**Comment by bbalan** [comment] 2023-06-09 20:18
I'm having the same issue after upgrading to v10. Works fine on Android, and worked on both in 8.5.0.

`"@rnmapbox/maps": "^10.0.8-rc.1"`

**Comment by jpitkanen17** [comment] 2023-07-03 11:03
I made this patch which fixed the issue for our usecase, pretty much just copied the usage of expressions from the other style methods.

```swift
diff --git a/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLStyleValue.swift b/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLStyleValue.swift
index 25b943e..cb5f445 100644
--- a/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLStyleValue.swift
+++ b/node_modules/@rnmapbox/maps/ios/RCTMGL-v10/RCTMGLStyleValue.swift
@@ -364,13 +364,22 @@ class RCTMGLStyleValue {
   }
   
   func mglStyleValueEnum<Enum : RawRepresentable>() -> Value<Enum> where Enum.RawValue == String {
-    if let value = value as? Dictionary<String,Any> {
-      let value = RCTMGLStyleValue.convert(value["stylevalue"] as! [String:Any])
-      return Value.constant(Enum(rawValue: value as! String)!)
-    } else {
-      Logger.log(level: .error, message:"Invalid value for enum: \(value) returning something")
+    guard let value = value as? Dictionary<String,Any> else {
+      Logger.log(level: .error, message: "Invalid value for array of strings: \(value)")
       return Value.constant(Enum(rawValue: value as! String)!)
     }
+    let valueObj = RCTMGLStyleValue.convert(value["stylevalue"] as! [String:Any])
+    do {
+        if valueObj is String {
+          return Value.constant(Enum(rawValue: valueObj as! String)!)
+        }
+        let data = try JSONSerialization.data(withJSONObject: valueObj, options: .prettyPrinted)
+        let decodedExpression = try JSONDecoder().decode(Expression.self, from: data)
+        return .expression(decodedExpression)
+    } catch {
+       Logger.log(level: .error, message: "Invalid value for array number: \(value) error: \(error) setting dummy value")
+       return Value.constant(Enum(rawValue: valueObj as! String)!)
+    }
   }
 
   func mglStyleEnum<Enum : RawRepresentable>() -> Enum where Enum.RawValue == String {```

**Closed** 2023-07-14 04:00 UTC
Labels: bug 🪲, iOS
