### ISSUE TITLE
Thread MapboxRenderThread was not started, ignoring event

### ISSUE THREAD

**Issue by TIEverton** [rnmapbox/maps#1992] opened 2022-06-22 11:35 UTC
**Describe the bug**  
The bug occurs when I navigate from the map screen to another screen and back to the map screen, after that the App crashes, I'm using react-navigation. The only error I was able to catch using Flipper was this: [maps-android\Mbgl-MapboxRenderThread]: Thread MapboxRenderThread was not started, ignoring event

**To Reproduce**  
I have no idea how to reproduce this

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 7.1.1
 - Device: 
 - Emulator/ Simulator: no
 - Dev OS: Win11
 - @rnmapbox/maps Version: last
 - Mapbox GL version: last
 - React Native Version: 0.68.2

**Additional context**

**Comment by portugaAndre** [comment] 2022-06-22 12:38
Having the same problem here.

**Comment by portugaAndre** [comment] 2022-06-28 11:04
We forced it to load when the screen is in focus, when it goes out of focus, it removes.
It is not the best solution either.

**Comment by Entryist** [comment] 2022-07-01 16:48
Same here. Temporary workaround: Add `detachInactiveScreens={false}` to Tab.Navigator:

```
  <Tab.Navigator
    initialRouteName='map'
    tabBar={(props) => <TabBar {...props} />}
    detachInactiveScreens={false}
  >
```

**Comment by portugaAndre** [comment] 2022-08-04 16:55
> Same here. Temporary workaround: Add `detachInactiveScreens={false}` to relevant navigators:
> 
> ```
>   <Tab.Navigator
>     initialRouteName='map'
>     tabBar={(props) => <TabBar {...props} />}
>     detachInactiveScreens={false}
>   >
> ```

this works for me, but when the app "sleeps" modal doesn't work anymore.

**Comment by creitmeier701x** [comment] 2022-08-12 15:24
> Same here. Temporary workaround: Add `detachInactiveScreens={false}` to relevant navigators:
> 
> ```
>   <Tab.Navigator
>     initialRouteName='map'
>     tabBar={(props) => <TabBar {...props} />}
>     detachInactiveScreens={false}
>   >
> ```

This seems to suppress the issue for me as well.
For me my bottom sheet modals appears to continue working. They do exist above the tab navigator though.

**Comment by mfazekas** [comment] 2022-09-16 08:40
Duplicate of #2212

**Closed by mfazekas** 2022-09-16 08:40 UTC
