### ISSUE TITLE
[Bug]: MarkerView disappears when deselecting and selecting again

### ISSUE THREAD

**Issue by MorganTrudeau** [rnmapbox/maps#2588] opened 2023-02-04 20:54 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

10.7.0

### Platform

iOS

### `@rnmapbox/maps` version

10.0.0-beta.65

### Standalone component to reproduce

The issue is MarkerView disappears when selected, deselected and selected again. I have reproduced this bug in my own app and the example app in this repo. To easily reproduce in the example app just change the ```MarkerView``` Component in ```src/examples/v10/Markers.tsx``` to the code below. Just change the onPress prop to select and deselect if already selected.

```
 <MarkerView
              key={`MarkerView-${marker.coords.join('-')}`}
              coordinate={marker.coords}
              anchor={anchor}
              allowOverlap={allowOverlap}
              isSelected={i === selectedIndex}
              style={{ display: show ? 'flex' : 'none' }}
            >
              <Pressable
                style={[
                  styles.markerBox,
                  { backgroundColor: marker.color, padding: 4 * size },
                ]}
                onPress={() => setSelectedIndex(index => index === i ? -1 : i)} // CHANGE THIS LINE
              >
                <Text style={styles.markerText}>Marker {i + 1}</Text>
              </Pressable>
            </MarkerView>
```

### Observed behavior and steps to reproduce

- Press a marker (Marker is selected as expected)
- Press the same marker again (Marker is deselected as expected)
- Press the same Marker again 

Observed behavior:
Marker is selected but disappears.

### Expected behavior

Expected behavior:
Marker is selected and remains visible.

### Notes / preliminary analysis

Important note. The marker reappears when you zoom or move the map. Once the map rerenders it shows again.

### Additional links and references

https://www.loom.com/share/c05942857083468083e065bee3b36fbe

**Comment by mfazekas** [comment] 2023-02-05 15:32
@MorganTrudeau Thanks much for the clear bug report. I was able to reproduce it and it seems to be fixed by switching to Mapbox selection support. That requires 10.9 or older. See #2589

**Closed** 2023-02-05 16:34 UTC
Labels: bug 🪲, iOS, v10
