### ISSUE TITLE
[Bug]: MapView onPress and onLongPress not working properly on Android

### ISSUE THREAD

**Issue by hernanmateo** [rnmapbox/maps#2750] opened 2023-03-30 14:30 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

10.12.1

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-rc5

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView,
  Camera,
} from '@rnmapbox/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView onPress={() => alert('onPress')} onLongPress={() => alert('onLongPress')} style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
      </MapView>
    );
  }
}
export BugReportExample;
```

### Observed behavior and steps to reproduce

I'm trying to use the onPress and onLongPress controllers in a MapView component with the following results:

- The onPress function is never called (even without the onLongPress callback declared)
- instead the onLongPress function is fired onPress and disables the ability to move the map

### Expected behavior

- The onPress function should be called when the user single presses on the map
- The onLongPress function should be called when the user presses and holds the map
- The map should move when the users drags the map, even if the previous function are declared on the MapView component

**Comment by mfazekas** [comment] 2023-04-01 15:30
@hernanmateo I could not reproduce the issue. Have you tried the component as is?
I've tried on simulator and on device in both case I've received the appropiate alert.

Can you clone our repo and run the example app, with the attached component in BugReportExample.js

**Comment by mfazekas** [comment] 2023-04-02 12:13
Closing as cannot reproduce

**Closed by mfazekas** 2023-04-02 12:13 UTC
Labels: Needs: Repro, Needs: Author Feedback
