### ISSUE TITLE
[Bug]: Crash when updating the iconRotate property on Android 

### ISSUE THREAD

**Issue by kopchikovich** [rnmapbox/maps#2874] opened 2023-05-19 11:32 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-rc.3

### Standalone component to reproduce

```javascript
import React, { useEffect, useState } from 'react'
import MapboxGL from '@rnmapbox/maps'
import CompassHeading from 'react-native-compass-heading'

const layerStyles = {
  normal: {
    pulse: {
      circleRadius: 15,
      circleColor: 'rgba(51, 181, 229, 100)',
      circleOpacity: 0.2,
      circlePitchAlignment: 'map',
    },
    background: {
      circleRadius: 9,
      circleColor: '#fff',
      circlePitchAlignment: 'map',
    },
    foreground: {
      circleRadius: 6,
      circleColor: 'rgba(51, 181, 229, 100)',
      circlePitchAlignment: 'map',
    },
    heading: {
      iconOffset: [0, -17],
      iconImage: 'headingIcon',
      iconAllowOverlap: true,
      iconPitchAlignment: 'map',
    }
  },
}

const normalIcon = (heading) => [
  <MapboxGL.CircleLayer
    key="mapboxUserLocationPluseCircle"
    id="mapboxUserLocationPluseCircle"
    style={layerStyles.normal.pulse}
  />,
  <MapboxGL.CircleLayer
    key="mapboxUserLocationWhiteCircle"
    id="mapboxUserLocationWhiteCircle"
    style={layerStyles.normal.background}
  />,
  <MapboxGL.CircleLayer
    key="mapboxUserLocationBlueCicle"
    id="mapboxUserLocationBlueCicle"
    style={layerStyles.normal.foreground}
  />,
  <MapboxGL.SymbolLayer
    key="mapboxUserLocationHeadingIndicator"
    id="mapboxUserLocationHeadingIndicator"
    style={{
      iconRotate: heading,
      ...layerStyles.normal.heading,
    }}
  />,
  <MapboxGL.Images images={{ headingIcon: 'path to img' }} />
]

const BugReportExample = () => {
  const [heading, setHeading] = useState(0)

  useEffect(() => {
    CompassHeading.start(3, ({ heading }) => {
      // Checking heading value just in case
      if (typeof heading === 'number' && heading >= 0 && heading <= 360) {
        setHeading(heading)
      }
    })

    return CompassHeading.stop
  }, [])

  return (
    <MapboxGL.UserLocation minDisplacement={1}>
      {normalIcon(heading)}
    </MapboxGL.UserLocation>
  )
}

export default BugReportExample

``` 

### Observed behavior and steps to reproduce

Some Android users have crashes related to updating the `iconRotate` property of the `MapboxGL.SymbolLayer` component inside `MapboxGL.UserLocation` after updating from `react-native-mapbox-gl/maps: 7.2.0` to `rnmapbox/maps: 10.0.0-rc.3`
Our crash rate increased by 10% We had to temporarily hide the arrow at UserLocation

I checked and added an extra check, we always pass the correct value, but the crashes keep happening. The difficulty is that there is no way to reproduce this error, there is only a stack trace from Google Play and Sentry

```
Exception com.facebook.react.bridge.JSApplicationIllegalArgumentException:
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:102)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:136)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:56)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:49)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties (NativeViewHierarchyManager.java:143)
  at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute (UIViewOperationQueue.java:93)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:908)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1019)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:47)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1079)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1299)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1309)
  at android.view.Choreographer.doCallbacks (Choreographer.java:923)
  at android.view.Choreographer.doFrame (Choreographer.java:847)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1283)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Method.invoke
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:87)
Caused by com.mapbox.maps.MapboxStyleException:
  at com.mapbox.maps.extension.style.layers.Layer.updateProperty (Layer.kt:152)
  at com.mapbox.maps.extension.style.layers.Layer.setProperty$extension_style_publicRelease (Layer.kt:141)
  at com.mapbox.maps.extension.style.layers.generated.SymbolLayer.iconRotate (SymbolLayer.kt:809)
  at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setIconRotate (RCTMGLStyleFactory.java:1318)
  at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setSymbolLayerStyle (RCTMGLStyleFactory.java:255)
  at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayer.addStyles (RCTMGLSymbolLayer.kt:31)
  at com.mapbox.rctmgl.components.styles.layers.RCTLayer.setReactStyle (RCTLayer.kt:118)
  at com.mapbox.rctmgl.components.styles.layers.RCTMGLSymbolLayerManager.setReactStyle (RCTMGLSymbolLayerManager.kt:60)
``` 

### Expected behavior

The application should not crash when updating a property and ideally We would like to get a clear error so I know how to fix it

**Comment by mfazekas** [comment] 2023-05-20 10:52
@kopchikovich first try with later version. 

Second the crash seems to be from here. 

https://github.com/mapbox/mapbox-maps-android/blob/v10.11.2/extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt#L152

Can you get the error message? To see what was the error?

I'm closing this as this is not something we can reproduce

**Closed by mfazekas** 2023-05-20 10:52 UTC
Labels: error-in-code

**Comment by olofholmlund** [comment] 2023-05-23 11:35
Im getting a similar issue on the latest version (10.0.6).

I'm using 
```
<MapboxGL.UserLocation
            visible={true}
            showsUserHeadingIndicator={true}
            animated={true}
            renderMode="normal"
/>
```

Its working on first load, but when I change mapbox style URL during runtime it crashes (on android) with the following error: 

```
Error while updating property 'reactStyle' of a view managed by: RCTMGLSymbolLayer

null

Set layer property "icon-rotation-alignment" failed: Layer mapboxUserLocationHeadingIndicator is not in style map
```

No issue on iOS.

If I disable heading indicator it does not crash the app, but I still get this error when changing styles:
```
Mapbox error Map load failed: {type=source, message=Source mapboxUserLocation is not in style, begin=9706101240} {"level": "error", "message": "Map load failed: {type=source, message=Source mapboxUserLocation is not in style, begin=9706101240}", "tag": "RCTMGLMapView"}
```


Any idea @mfazekas ? Thanks
