### ISSUE TITLE
[Bug]: ShapeSource.tsx: Unexpected token (157:36)

### ISSUE THREAD

**Issue by leonardofrmello** [rnmapbox/maps#2547] opened 2023-01-17 15:03 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

iOS, Android

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

   "react": "17.0.2"
   "react-native": "0.66.4"
    "@rnmapbox/maps": "10.0.0-beta.64",

/node_modules/@rnmapbox/maps/javascript/components/ShapeSource.tsx: Unexpected token (157:36)

  155 |  */
  156 | export class ShapeSource extends NativeBridgeComponent(
> 157 |   AbstractSource<Props, NativeProps>,
      |                                     ^
  158 |   NATIVE_MODULE_NAME,
  159 | ) {
  160 |   static NATIVE_ASSETS_KEY = 'assets';

### Observed behavior and steps to reproduce

- I updated the lib from version 8.5.0 to 10.0.0-beta.64
- Error happens when running the app.

**Comment by mfazekas** [comment] 2023-01-17 15:06
Duplicate of #2423

**Comment by leonardofrmello** [comment] 2023-01-18 12:20
Now I have another problem.
ShapeSource.tsx: Unknown node type: "TSInstantiationExpression"
I've tried all the possibilities I found in this forum and without success.

**Closed** 2023-01-22 05:55 UTC

**Comment by Stophface** [comment] 2023-04-30 10:55
@leonardofrmello did you solve this?

**Comment by leonardofrmello** [comment] 2023-05-22 19:39
@Stophface yes, but now i need update my react and i have the same problem.
