### ISSUE TITLE
[Bug]: setCamera padding does not have an effect

### ISSUE THREAD

**Issue by nixolas1** [rnmapbox/maps#2572] opened 2023-01-31 13:52 UTC
### Mapbox Implementation

Mapbox

### Mapbox Version

default

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.64

### Standalone component to reproduce

```javascript

import React, {useEffect, useRef} from "react"
import MapboxGL from "@rnmapbox/maps"
const BugReportExample = () => {
  const camera = useRef(null)

  useEffect(() => {
    if(camera.current) {
      camera.current?.setCamera({
        centerCoordinate: [-74.00597, 40.71427],
        padding: {paddingTop: 1000},
        animationDuration: 5000,
      })
    }
  }, [camera])

  return (
    <MapboxGL.MapView style={{flex: 1}}>
      <MapboxGL.Camera ref={camera} centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
    </MapboxGL.MapView>
  );
}
```

### Observed behavior and steps to reproduce

Padding config on setCamera does nothing. Works on v10 iOS and v8 android.
Applies to all padding directions, paddingTop, paddingBottom, paddingLeft and paddingRight

### Expected behavior

In the example the camera should be different from the normal starting position, but is not.

**Comment by veb-ioki** [comment] 2023-02-02 07:52
Can confirm, not applied on Android, see https://github.com/rnmapbox/maps/issues/2554#issuecomment-1413281868
On iOS it works fine.

**Comment by kneza23** [comment] 2023-03-01 10:11
Yeah it does not work on Android

**Comment by KiwiKilian** [comment] 2023-03-02 09:13
Duplicate of #2339

**Closed by KiwiKilian** 2023-03-02 09:13 UTC
