### ISSUE TITLE
react-native : andorid build crash - Android version - above 11

### ISSUE THREAD

**Issue by deepakshrma30** [rnmapbox/maps#3564] opened 2024-07-04 12:29 UTC
## Environment
- Dev OS: MAC OS
- @rnmapbox/maps version: 10.1.27 
- React Native version: 0.70.6
- Android version - above 11

Issue : Trying to implement and mapbox in my app and build is crashing and no error is given in the console

This is the code which is inside the build.gradle
```
maven {
            // Android JSC is installed from npm
            // url("$rootDir/../node_modules/jsc-android/dist")
             url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                  password = project.hasProperty('MAPBOX_DOWNLOADS_TOKEN') ? project.MAPBOX_DOWNLOADS_TOKEN : ''
            }
        }
ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
         
         RNMapboxMapsVersion = '11.0.0'
        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
```

**Comment by mfazekas** [comment] 2024-07-04 13:06
Hi, thanks for the report!

It's not clear if the build is crashing or that app itself is crashing. Also take a look at native console - logcat for directions on the crash. 

To be able to look into setup related issues we need full steps to reproduce the issue. 
Ideally n a brand new project, in the form of
```
react-native init sample --version react-native@0.67.5
cd sample
npm install @rnmapbox/maps --save
cd ios
pod installl
...
react-native run-ios
```

closing the issue now, will reopen when you provide the steps to reproduce.
If you cannot reproduce with a  brand new project, please start a new project with the same rn version you have and compare package.json for different versions.

Please note that your issue is considered a [support request](https://github.com/rnmapbox/maps/wiki/Support) and we don't provide free [support](https://github.com/rnmapbox/maps/wiki/Support). Thanks for the understanding.

**Closed by mfazekas** 2024-07-04 13:06 UTC
Labels: bug-setup 🪲
